name: coffe_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: sora
      fonts:
        - asset: assets/font/Sora-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Sora-Bold.ttf
          weight: 700
        - asset: assets/font/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/font/Sora-Medium.ttf
          weight: 500
        - asset: assets/font/Sora-Regular.ttf
          weight: 400
        - asset: assets/font/Sora-Light.ttf
          weight: 300
        - asset: assets/font/Sora-Thin.ttf
          weight: 200
        - asset: assets/font/Sora-ExtraLight.ttf
          weight: 100
